FROM node:20-alpine
WORKDIR /app
COPY ../../package.json ../../pnpm-lock.yaml ./
RUN corepack enable && corepack prepare pnpm@latest --activate && pnpm fetch
COPY ../../ ./
WORKDIR /app/apps/web
EXPOSE 3000
CMD ["pnpm","start"]
