[phases.setup]
nixPkgs = ['nodejs_20', 'pnpm']

[phases.install]
cmds = [
  'pnpm install --no-frozen-lockfile'
]

[phases.build]
cmds = [
  'pnpm run build:railway'
]

[start]
cmd = 'pnpm run start:railway'
