[variables]
NIXPACKS_NO_CACHE = '1'
NIXPACKS_METADATA = "node=20,pnpm=latest"
FORCE_REBUILD = "2024-12-31-v10"

[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
cmds = [
  "pnpm install --no-frozen-lockfile --force"
]

[phases.build]
cmds = [
  "pnpm -r --filter \"./frontend\" build || echo 'Frontend build failed, continuing...'",
  "pnpm -r --filter \"./apps/server\" build",
  "rm -rf apps/server/public && mkdir -p apps/server/public",
  "ls -la frontend/ || echo 'Frontend directory not found'",
  "if [ -d frontend/dist ] && [ \"$(ls -A frontend/dist)\" ]; then cp -r frontend/dist/* apps/server/public/; else echo 'Creating minimal index.html fallback'; echo '<!DOCTYPE html><html><head><title>AI Interviewer</title></head><body><h1>AI Interviewer Platform</h1><p>Server is running. Frontend build in progress.</p><script>setTimeout(() => location.reload(), 5000);</script></body></html>' > apps/server/public/index.html; fi"
]

[start]
cmd = "node apps/server/dist/index.js"
