[variables]
NIXPACKS_NO_CACHE = '1'

[phases.setup]
nixPkgs = ['nodejs_20', 'pnpm']

[phases.install]
cmds = [
  'echo "Force rebuild timestamp: $(date)"',
  'pnpm install --no-frozen-lockfile --force'
]

[phases.build]
cmds = [
  'echo "Building with nixpacks - no Docker"',
  'pnpm run build:railway'
]

[start]
cmd = 'pnpm run start:railway'
